// <auto-generated />
using System;
using LabiryntBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LabiryntBackend.Migrations
{
    [DbContext(typeof(GBMazeContext))]
    [Migration("20230613205441_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LabiryntBackend.Models.Maze", b =>
                {
                    b.Property<long>("id_maze")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id_maze"));

                    b.Property<long?>("cols")
                        .HasColumnType("bigint");

                    b.Property<string>("exitCoords")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("id_user")
                        .HasColumnType("bigint");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("rows")
                        .HasColumnType("bigint");

                    b.Property<int?>("seed")
                        .HasColumnType("int");

                    b.Property<string>("startXY")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_maze");

                    b.ToTable("Mazes");
                });

            modelBuilder.Entity("LabiryntBackend.Models.User", b =>
                {
                    b.Property<long>("id_user")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("id_user"));

                    b.Property<string>("login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_user");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
